allowBuilds:
  esbuild: true
  sharp: false
  unrs-resolver: false
minimumReleaseAgeExclude:
  - '@aws-sdk/client-s3@3.1125.0'
  - '@aws-sdk/s3-presigned-post@3.1125.0'
  - '@aws-sdk/s3-request-presigner@3.1125.0'
  - '@clerk/backend@3.17.1'
  - '@clerk/nextjs@7.9.0'
  - '@clerk/react@6.15.0'
  - '@clerk/shared@4.31.0'
  - lucide-react@1.40.0
  - '@types/react-dom@19.2.7'
  - shadcn@4.20.1
